INSERT INTO institutions (description, name) VALUES ('Cel i misja: Pomoc dzieciom z ubogich rodzin.','Fundacja "Dbam o Zdrowie"');
INSERT INTO institutions (description, name) VALUES ('Cel i misja: Pomoc wybudzaniu dzieci ze śpiączki.','Fundacja "A kogo"');
INSERT INTO institutions (description, name) VALUES ('Cel i misja: Pomoc osobom znajdującym się w trudnej sytuacji życiowej.','Fundacja “Dla dzieci"');
INSERT INTO institutions (description, name) VALUES ('Cel i misja: Pomoc dla osób nie posiadających miejsca zamieszkania','Fundacja “Bez domu”');
INSERT INTO institutions (description, name) VALUES ('Cel i misja: Zrobić jak najlepiej projekt w ramach Portfolio Lab','Fundacja "Mam marzenie"');
INSERT INTO categories(name) VALUE ('ubrania');
INSERT INTO categories(name) VALUE ('gry komputerowe');
INSERT INTO categories(name) VALUE ('zabawki');
INSERT INTO categories(name) VALUE ('książki');
INSERT INTO categories(name) VALUE ('jedzenie');
INSERT INTO donations(quantity) VALUE (1);
INSERT INTO donations(quantity) VALUE (4);
INSERT INTO donations(quantity) VALUE (2);
INSERT INTO donations(quantity) VALUE (6);